name: rsmetrics
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2022.3.18
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.3
  - openssl=1.1.1n
  - pip=21.2.4
  - python=3.9.11
  - readline=8.1.2
  - setuptools=58.0.4
  - sqlite=3.38.0
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - beautifulsoup4==4.10.0
    - certifi==2022.12.7
    - charset-normalizer==2.0.12
    - click==8.1.3
    - flask==2.1.2
    - flask-pymongo==2.3.0
    - idna==3.3
    - importlib-metadata==4.11.4
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - markupsafe==2.1.1
    - natsort==8.1.0
    - numpy==1.22.3
    - pandas==1.4.2
    - pyarrow==10.0.1
    - pymongo==4.1.0
    - pymongoarrow==0.6.2
    - python-dateutil==2.8.2
    - python-dotenv==0.20.0
    - pytz==2022.1
    - pyyaml==6.0
    - requests==2.27.1
    - scipy==1.8.0
    - six==1.16.0
    - soupsieve==2.3.2
    - urllib3==1.26.9
    - werkzeug==2.1.2
    - zipp==3.8.0
